import type { Settings } from "~/models";

export const decodeGrade = (item: any): Settings => {
  const params = item.parametrage;

  return {
    evaluationColors: {
      eval1: params.couleurEval1,
      eval2: params.couleurEval2,
      eval3: params.couleurEval3,
      eval4: params.couleurEval4,
    },
    evaluationLabels: {
      eval1: params.libelleEval1,
      eval2: params.libelleEval2,
      eval3: params.libelleEval3,
      eval4: params.libelleEval4,
    },
    averageDisplay: params.affichageMoyenne,
    averageHomeworkDisplay: params.affichageMoyenneDevoir,
    subjectPositionDisplay: params.affichagePositionMatiere,
    competenceTabDisplay: params.affichageOngletCompetence,
    gradeDisplay: params.affichageNote,
    competenceDisplay: params.affichageCompetence,
    evaluationComponentsDisplay: params.affichageEvaluationsComposantes,
    componentGraphDisplay: params.affichageGraphiquesComposantes,
    componentGraphCalculationMode: params.modeCalculGraphiquesComposantes,
    numericCompetenceDisplay: params.affichageCompNum,
    numericCompetenceLabels: {
      label1: params.libelleEvalCompNum1,
      label2: params.libelleEvalCompNum2,
      label3: params.libelleEvalCompNum3,
    },
    appreciationDisplay: params.affichageAppreciation,
    teacherAppreciations: params.appreciationsProf,
    mainTeacherAppreciation: params.appreciationProfPrinc,
    mentionDisplay: params.affichageMention,
    appreciationCE: params.affichageAppreciationCE,
    appreciationVS: params.affichageAppreciationVS,
    appreciationCN: params.affichageAppreciationCN,
    appreciationClass: params.affichageAppreciationClasse,
    appreciationClosedPeriod: params.affichageAppreciationPeriodeCloturee,
    averageOnlyForClosedPeriod: params.moyenneUniquementPeriodeCloture,
    averagePeriodStatement: params.moyennePeriodeReleve,
    annualAveragePeriod: params.moyennePeriodeAnnuelle,
    averageOutsidePeriods: params.moyennePeriodeHorsP,
    studentAverageInGrades: params.moyenneEleveDansNotes,
    studentAverage: params.moyenneEleve,
    studentAverageInGlobalAverage: params.moyenneEleveDansMoyenne,
    generalAverage: params.moyenneGenerale,
    subjectCoefficientAverage: params.moyenneCoefMatiere,
    classAverage: params.moyenneClasse,
    minimumAverage: params.moyenneMin,
    maximumAverage: params.moyenneMax,
    rankAverage: params.moyenneRang,
    averageOutOf: params.moyenneSur,
    averageGraph: params.moyenneGraphique,
    simulationAverages: params.moyennesSimulation,
    gradeCoefficient: params.coefficientNote,
    subjectCoefficientColumn: params.colonneCoefficientMatiere,
    boldGradesBelowAverage: params.noteGrasSousMoyenne,
    boldGradesAboveAverage: params.noteGrasAudessusMoyenne,
    assignmentLabels: params.libelleDevoir,
    assignmentDates: params.dateDevoir,
    assignmentTypes: params.typeDevoir,
    gradesOnlyForClosedPeriods: params.noteUniquementPeriodeCloture,
    gradesPeriodStatement: params.notePeriodeReleve,
    annualGradesPeriod: params.notePeriodeAnnuelle,
    gradesOutsidePeriods: params.notePeriodeHorsP,
    appreciationLabels: params.libellesAppreciations,
  };
};
