export type Period = Readonly<{
  id: string;
  name: string;
  yearly: boolean;
  isMockExam: boolean;
  isEnded: boolean;
  startDate: Date;
  endDate: Date;
  councilDate?: Date;
  councilStartHour?: string;
  councilEndHour?: string;
  councilClassroom?: string;
  ensembleSubjects?: {
    calculationDate: string;
    overallAverage?: string;
    classAverage?: string;
    minAverage?: string;
    maxAverage?: string;
    classRepresentativeName: string;
    classRepresentativeAppreciation?: string;
    classSupervisorName: string;
    classSupervisorAppreciation?: string;
    supervisorAppreciation?: string;
    councilDecision: string;
    rank?: string;
    classStrength?: string;
    overallClassAppreciation?: string;
    subjects: Array<string>;
    simulatedSubjects: Array<unknown>;
  };
}>;
